# Generated by Django 5.2.2 on 2025-08-19 11:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator])),
                ('contact', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, max_length=255, null=True)),
                ('github', models.URLField(blank=True, max_length=255, null=True)),
                ('portfolio', models.URLField(blank=True, max_length=255, null=True)),
                ('blog', models.URLField(blank=True, max_length=255, null=True)),
                ('education', models.CharField(max_length=255)),
                ('experience', models.PositiveIntegerField(blank=True, default=0)),
                ('current_designation', models.CharField(blank=True, max_length=255, null=True)),
                ('current_organization', models.CharField(blank=True, max_length=255, null=True)),
                ('current_ctc', models.FloatField(blank=True, default=0, max_length=255)),
                ('current_ctc_ih', models.FloatField(blank=True, default=0, max_length=255)),
                ('expected_ctc', models.FloatField(blank=True, default=0, max_length=255)),
                ('expected_ctc_ih', models.FloatField(blank=True, default=0, max_length=255)),
                ('offer_in_hand', models.FloatField(blank=True, default=0, max_length=255)),
                ('notice_period', models.PositiveIntegerField(blank=True, default=0)),
                ('reason_for_change', models.CharField(blank=True, max_length=500, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('upload_resume', models.FileField(null=True, upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc'], message='Select pdf, docx or doc files only')])),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('text_content', models.TextField(default='')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_new', models.BooleanField(default=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='users.company')),
                ('job_openings', models.ManyToManyField(blank=True, null=True, to='manager.jobopening')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.JSONField(null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='candidate.candidate')),
                ('job_opening', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.jobopening')),
            ],
        ),
    ]
