# Generated by Django 5.2.2 on 2025-08-19 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate', '0001_initial'),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'interviewbot_resumeanalysis',
            },
        ),
        migrations.CreateModel(
            name='OldAssignEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'interviewbot_jobopening_assignemployee',
            },
        ),
        migrations.CreateModel(
            name='OldCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'interviewbot_candidate',
            },
        ),
        migrations.CreateModel(
            name='OldCandidateJobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'interviewbot_candidate_job_openings',
            },
        ),
        migrations.CreateModel(
            name='OldClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'interviewbot_client',
            },
        ),
        migrations.CreateModel(
            name='OldCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'interviewbot_company',
            },
        ),
        migrations.CreateModel(
            name='OldEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'interviewbot_employee',
            },
        ),
        migrations.CreateModel(
            name='OldJobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'interviewbot_jobopening',
            },
        ),
        migrations.CreateModel(
            name='InterviewAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('given_answer', models.TextField()),
                ('audio_transcript', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='interviews/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('question_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('skill_scores', models.JSONField(blank=True, null=True)),
                ('technical_skills_score', models.DecimalField(blank=True, decimal_places=2, help_text='Score (0–100) representing overall technical skill demonstrated.', max_digits=5, null=True)),
                ('source', models.CharField(choices=[('job', 'Job'), ('resume', 'Resume')], default='job', max_length=20)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_answers', to='candidate.candidate')),
                ('job_opening', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.jobopening')),
                ('resume_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_answers', to='candidate.resumeanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_selected', models.BooleanField(default=False)),
                ('is_custom', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='manager.jobopening')),
            ],
        ),
    ]
