# Generated by Django 5.1 on 2025-06-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewanswer',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='interviews/'),
        ),
    ]
