# Generated by Django 5.2.2 on 2025-08-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oldanalysis',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='oldassignemployee',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='oldcandidate',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='oldcandidatejobopening',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='oldclient',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='oldcompany',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='oldemployee',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='oldjobopening',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='oldanalysis',
            name='temp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oldassignemployee',
            name='temp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oldcandidate',
            name='temp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oldcandidatejobopening',
            name='temp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oldclient',
            name='temp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oldcompany',
            name='temp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oldemployee',
            name='temp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oldjobopening',
            name='temp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
