# Generated by Django 5.2.2 on 2025-08-19 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviewbot', '0002_alter_oldanalysis_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OldAnalysis',
        ),
    ]
