# Generated by Django 5.1 on 2025-06-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewbot', '0002_interviewanswer_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewanswer',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
