# Generated by Django 5.1 on 2025-07-02 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewbot', '0003_alter_interviewanswer_is_correct'),
        ('manager', '0008_alter_jobopening_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewanswer',
            name='job_opening',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.jobopening'),
        ),
    ]
