# Generated by Django 5.1 on 2025-07-02 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviewbot', '0004_interviewanswer_job_opening'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewanswer',
            name='correct_answer',
        ),
    ]
