# Generated by Django 5.1 on 2025-07-04 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0010_alter_candidate_job_openings_and_more'),
        ('interviewbot', '0005_remove_interviewanswer_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewanswer',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_answers', to='candidate.candidate'),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='resume_analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_answers', to='candidate.resumeanalysis'),
        ),
    ]
