# Generated by Django 5.1 on 2025-07-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewbot', '0006_interviewanswer_candidate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewanswer',
            name='audio_transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
