# Generated by Django 5.1 on 2025-07-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewbot', '0007_interviewanswer_audio_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewanswer',
            name='question_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='skill_scores',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='technical_skills_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Score (0–100) representing overall technical skill demonstrated.', max_digits=5, null=True),
        ),
    ]
