# Generated by Django 5.1 on 2025-07-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewbot', '0009_interviewquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewanswer',
            name='source',
            field=models.CharField(choices=[('job', 'Job'), ('resume', 'Resume')], default='job', max_length=20),
        ),
    ]
