# Generated by Django 5.2.2 on 2025-08-19 11:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import manager.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('location', models.CharField(blank=True, max_length=400)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator])),
                ('contact', models.CharField(blank=True, max_length=12)),
                ('website', models.URLField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
            ],
        ),
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('openings', models.PositiveIntegerField(validators=[manager.models.exempt_zero])),
                ('requiredskills', models.TextField(blank=True)),
                ('min_experience', models.PositiveIntegerField(default=0)),
                ('max_experience', models.PositiveIntegerField(default=1)),
                ('education', models.CharField(blank=True, default='graduate', max_length=255)),
                ('jobdescription', models.FileField(blank=True, upload_to='jd/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'txt'], message='Select pdf, docx, doc or txt files only')])),
                ('budget', models.FloatField(default=0)),
                ('job_type', models.CharField(blank=True, choices=[('Contractual', 'Contractual'), ('Permanent', 'Permanent')], max_length=50)),
                ('job_mode', models.CharField(blank=True, choices=[('Office', 'Office'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], max_length=50)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('jd_content', models.TextField(blank=True)),
                ('content_type', models.CharField(blank=True, choices=[('file', 'File'), ('text', 'Text')], max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('expires', models.IntegerField(default=21)),
                ('skills_criteria', models.IntegerField(default=50)),
                ('hiring_for', models.CharField(choices=[('self', 'Hiring for self'), ('client', 'Hiring for client')], default='self', max_length=10)),
                ('assignemployee', models.ManyToManyField(to='users.employee')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
                ('created_by', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='jobopening', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_on'],
            },
        ),
    ]
